from django.shortcuts import render, redirect
from .models import Resume
import PyPDF2
from django.http import HttpResponse
from reportlab.pdfgen import canvas

def home(request):
    if request.method == 'POST':
        file = request.FILES.get('file')
        text = ""

        if file and file.name.endswith('.pdf'):
            reader = PyPDF2.PdfReader(file)
            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text.lower()

        keywords = {
            "python":30,
            "django":25,
            "sql":20,
            "html":10,
            "css":10,
            "javascript":15,
            "machine learning":30,
            "excel":10,
            "power bi":20
        }

        found = []
        score = 0

        for key,val in keywords.items():
            if key in text:
                found.append(key)
                score += val

        if score > 100:
            score = 100

        Resume.objects.create(
            name="Candidate",
            email="hidden@email.com",
            skills=", ".join(found),
            file=file,
            score=score
        )

        return redirect('/')

    data = Resume.objects.all()
    top = Resume.objects.order_by('-id').first()

    tips = []
    missing = 0
    issues = 0
    parse_rate = 0
    rank = "Beginner"

    if top:
        all_skills = ["python","django","sql","html","css","javascript"]
        found_skills = top.skills.lower()

        for s in all_skills:
            if s not in found_skills:
                missing += 1

        if top.score < 50:
            issues = 5
            parse_rate = 55
            rank = "Beginner"
            tips.append("Add more technical keywords.")
            tips.append("Improve ATS readability.")
        elif top.score < 80:
            issues = 2
            parse_rate = 78
            rank = "Intermediate"
            tips.append("Add projects and achievements.")
        else:
            issues = 0
            parse_rate = 95
            rank = "Advanced"
            tips.append("Excellent ATS-ready resume.")

    return render(request,'home.html',{
        'data':data,
        'top':top,
        'tips':tips,
        'missing':missing,
        'issues':issues,
        'parse_rate':parse_rate,
        'rank':rank
    })

def delete_resume(request,id):
    Resume.objects.get(id=id).delete()
    return redirect('/')

def edit_resume(request,id):
    return redirect('/')

def download_report(request,id):
    resume = Resume.objects.get(id=id)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=\"resume_report.pdf\"'

    p = canvas.Canvas(response)
    p.setFont("Helvetica-Bold",18)
    p.drawString(180,800,"Resume Analysis Report")

    p.setFont("Helvetica",12)
    p.drawString(50,750,f"Candidate: {resume.name}")
    p.drawString(50,725,f"Skills: {resume.skills}")
    p.drawString(50,700,f"Score: {resume.score}%")
    p.drawString(50,675,"Generated by Smart Resume Analyzer")

    p.showPage()
    p.save()

    return response